/*
 * This Java source file was generated by the Gradle 'init' task.
 */

class Fruit {}
class Apple extends Fruit {}

public class CheckEx {
    public static void main(String[] args ) {
        Fruit f = new Fruit();
        Apple a = new Apple();
        
        System.out.println(f.getClass());
        System.out.println(Fruit.class);
        System.out.println(a.getClass());
        System.out.println(Apple.class);
        f = (Fruit) a;
        a = (Apple) f;
        
        System.out.println(f.getClass());
        System.out.println(Fruit.class);
        System.out.println(a.getClass());
        System.out.println(Apple.class);
        boolean t = f.getClass().equals(Fruit.class);
        boolean z = f.getClass().equals(Apple.class);
        System.out.println(t);
        System.out.println(z);
    }
}