/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {

        final int LIMIT = 100;
        int[] sieve = new int[LIMIT + 1];
        sieve[0] = 1;
        sieve[1] = 1;

        
        for (int i = 2; i <= LIMIT; i++) {
            if (sieve[i] == 1) {
                continue;
            }

            int sqrtI = (int) Math.sqrt(i);

            for (int j = 2; j <= sqrtI; j++) {
                if (i % j == 0) {
                    int k = 1;

                    while (i * k <= LIMIT) {
                        sieve[i * k] = 1;
                        k++;
                    }

                    break;
                }
            }
        }

        for (int i = 1; i <= LIMIT; i++) {
            if (sieve[i] == 0) {
                System.out.println(i);
            }
        }

    }
}
